### ISSUE TITLE
Post video/photo

### ISSUE THREAD

**Issue by sanjeetbisht** [socialAPIS/Instagram-API#1]
Hey, How to post video/ photo on my insta account using this API?

**Comment by socialAPIS** [comment]
It is not implemented, but in next commit i will implement it.

**Comment by sanjeetbisht** [comment]
Okay, thanks.

**Comment by socialAPIS** [comment]
Here you have how to upload a photo [https://github.com/socialAPIS/Instagram-API/blob/master/examples/uploadImageExample.php](uploadImageExample).
and with the video upload i need to investigate other day.

**Comment by sanjeetbisht** [comment]
Hey, 
I used your sample. 
Got this error.


PHP Fatal error:  Uncaught Error: Call to undefined method InstagramFollowers\Request\MediaRequest::UploadPhoto() in C:\xampp\htdocs\instaapi\index.php:11
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\instaapi\index.php on line 11

Fatal error: Uncaught Error: Call to undefined method InstagramFollowers\Request\MediaRequest::UploadPhoto() in C:\xampp\htdocs\instaapi\index.php:11
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\instaapi\index.php on line 11

**Comment by socialAPIS** [comment]
You need first to instantiate in instagram.php
See the example https://github.com/socialAPIS/Instagram-API/blob/master/examples/uploadImageExample.php

Just change the image and your username and password, and check your package version.

**Comment by sanjeetbisht** [comment]
Hello,
I have latest version installed via composer. I have used your exact same code as yours. I just changed the username and password and the image name. Everything was the same. 


Fatal error: Uncaught Error: Call to undefined method InstagramFollowers\Request\MediaRequest::UploadPhoto() in C:\xampp\htdocs\instaapi\upload.php:11 Stack trace: #0 {main} thrown in C:\xampp\htdocs\instaapi\upload.php on line 11

**Comment by socialAPIS** [comment]
Something is then Wrong with composer on your side.

Try git clone this repo then composer install.

I tested it now and everything worked, i followed the steps and used my example.

You're doing something wrong.

**Comment by sanjeetbisht** [comment]
Okay, I was trying it on local. Let me try it on some server.

**Comment by socialAPIS** [comment]
It should work also local

**Comment by socialAPIS** [comment]
It should work local also

Try this:

Delete everything from your htdocs folder it should be empty
Open your command line and type: 
`git clone https://github.com/socialAPIS/Instagram-API.git ./`
`composer install`

go then to the example folder put an jpg with name `blur.JPG`
change username and password in the uploadImageExample.php file
open your command again
`cd c:\xampp\htdocs\example`
`php uploadImageExample.php`

**Comment by sanjeetbisht** [comment]
Ohh yeah, it worked thanks, man.

**Comment by sanjeetbisht** [comment]
Working from the server too.
Just getting these warning messages 

```
Warning: mkdir(): File exists in /home/xbysevvy/instadata/src/Repositories/Repository.php on line 48

Warning: chmod(): No such file or directory in /home/xbysevvy/instadata/src/Repositories/Repository.php on line 49
```

and these 2 lines repeated 58 times but image was published.

**Comment by socialAPIS** [comment]
We will fix this in the next commit

**Comment by sanjeetbisht** [comment]
Thanks. :)

**Comment by sanjeetbisht** [comment]
Please add it for video also. :)
