### ISSUE TITLE
proxy using ?

### ISSUE THREAD

**Issue by tenet912** [socialAPIS/Instagram-API#11]
hey bro . this script is support using proxy ?

**Comment by socialAPIS** [comment]
Yes, put it in request.php

**Comment by tenet912** [comment]
> 
> 
> Yes, put it in request.php

please make an example .

**Comment by socialAPIS** [comment]
Open Request.php
find following on Line: 59
    /**
     * @var $proxy string|null
     */
    protected $proxy = "Proxy IP:Proxy Port";
