### ISSUE TITLE
Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by luckydevilru** [socialAPIS/Instagram-API#14]
`Fatal error: Uncaught Exception in /home/a/autoli07/rus-mould.ru/public_html/vendor/socialapis/instagram-api/src/Instagram.php:326 Stack trace: #0 /home/a/autoli07/rus-mould.ru/public_html/vendor/socialapis/instagram-api/src/Instagram.php(247): InstagramFollowers\Instagram->_login('*******', '*******') 
#1 /home/a/autoli07/rus-mould.ru/public_html/vendor/socialapis/instagram-api/src/Instagram.php(182): InstagramFollowers\Instagram->checkAndRelogin('*******', '*******', false) 
#2 /home/a/autoli07/rus-mould.ru/public_html/insta.php(11): InstagramFollowers\Instagram->login('*******', '*******') 
#3 {main} thrown in /home/a/autoli07/rus-mould.ru/public_html/vendor/socialapis/instagram-api/src/Instagram.php on line 326
`

and the line vendor/socialapis/instagram-api/src/Instagram.php on line 326  gave the error

**> Please wait a few minutes before you try again.**

**Comment by socialAPIS** [comment]
You have been rate limited. For some reason your account or your IP have sent too many requests to the server.
