### ISSUE TITLE
change profile photo

### ISSUE THREAD

**Issue by nrucel** [socialAPIS/Instagram-API#2]
Hello, can you also add a profile photo replacement?

**Comment by socialAPIS** [comment]
I don't have much time at the moment, but next week I will try to implement this function for you.

try to reverse the Instagram v133.0.0.32.120, you just need to find the extra parameters for the image change. the others like csrf, device_id, phone_id, _uid, guid are in the app already, just pass the params and create a pull request.

**Comment by nrucel** [comment]
Severity:    Warning
Message:     mkdir(): File exists
File:  ../vendor/socialapis/instagram-api/src/Repositories/Repository.php

repeatedly giving this error on every login. This error exists when I log in with the same account

**Comment by socialAPIS** [comment]
> Severity: Warning
> Message: mkdir(): File exists
> Filename: ../vendor/socialapis/instagram-api/src/Repositories/Repository.php
> Line Number: 48
> 
> repeatedly giving this error on every login. This error exists when I log in with the same account

Did you git clone this repo or you're using the v1.0.0 from composer require?

**Comment by nrucel** [comment]
I installed with composer. works smoothly but gives warning in every transaction

**Comment by socialAPIS** [comment]
> I installed with composer. works smoothly but gives warning in every transaction

Yeah you are using the first version and not the dev-master . il push the new version today, then just update and it will be fixed

**Comment by socialAPIS** [comment]
> I installed with composer. works smoothly but gives warning in every transaction

Just update your packages. I think this will fix your problem `composer update socialapis/instagram-api`

**Comment by socialAPIS** [comment]
> Hello, can you also add a profile photo replacement?

 [Here](https://github.com/socialAPIS/Instagram-API/blob/master/examples/changeProfilePicture.php) you can see the example how to change the profile image

**Comment by nrucel** [comment]
Severity:    Warning
Message:     mkdir(): File exists
I updated it and this error repeatedly occurs when I log in

**Comment by socialAPIS** [comment]
> Severity: Warning
> Message: mkdir(): File exists
> I updated it and this error repeatedly occurs when I log in
> 
> where are the cookie information stored ? only records Device information ?
> 
> A PHP Error was encountered
> 
> Severity: Warning
> Message: mkdir(): File exists
> Filename: ....../vendor/socialapis/instagram-api/src/Repositories/Repository.php
> Line Number: 48
> 
> Backtrace:
> File: ....../vendor/socialapis/instagram-api/src/Repositories/Repository.php
> Line: 48
> Function: mkdir
> 
> ```
>     File: ....../vendor/socialapis/instagram-api/src/Repositories/CookiesStorageRepository.php
>     Line: 10
>     Function: openFolder
> 
>     File: ....../vendor/socialapis/instagram-api/src/Request.php
>     Line: 184
>     Function: saveCookies
> 
>     File: ....../vendor/socialapis/instagram-api/src/Request.php
>     Line: 449
>     Function: saveCookies
> 
>     File: ....../vendor/socialapis/instagram-api/src/Request.php
>     Line: 364
>     Function: _req
> 
>     File: ....../vendor/socialapis/instagram-api/src/Request/AccountRequest.php
>     Line: 76
>     Function: post
> 
>     File: ....../vendor/socialapis/instagram-api/src/Instagram.php
>     Line: 232
>     Function: process_contact_point_signals
> 
>     File: ....../vendor/socialapis/instagram-api/src/Instagram.php
>     Line: 248
>     Function: _postLoginFlow
> 
>     File: ....../vendor/socialapis/instagram-api/src/Instagram.php
>     Line: 182
>     Function: checkAndRelogin
> ```

I cannot recreate this error, can you tell me which PHP version you're using and are you on windows?

**Comment by nrucel** [comment]
the same error persists

**Comment by socialAPIS** [comment]
I think i can close this issue?
