### ISSUE TITLE
People follow/unfollow

### ISSUE THREAD

**Issue by sanjeetbisht** [socialAPIS/Instagram-API#3]
Can you please update code so that we can have the feature to follow and unfollow people?

Thanks in advance. :)

**Comment by socialAPIS** [comment]
We have this Feature. This was the First Feature i have implemented. I build actually this project just for following other people, you have for following and data collecting good options

**Comment by sanjeetbisht** [comment]
Hello, in PeopleRequest I can't find it. Can you upload the sample for follow and unfollow?

**Comment by socialAPIS** [comment]
If i have free time i will post samples. Try to search for function create_friendship($user_pk) in peopleRequests.php

There you can add besties, show many friendships but i think i don't have the function to unfollow 😩

But it will come, free feel to pull some code if you want

**Comment by sanjeetbisht** [comment]
Ohh I was confused by the name create_friendship, in another repo, it was direct follow and unfollow.  Will work on it and check it. 

I really wanna help you guys with adding more codes but I don't know how to reverse the Instagram v133. If you can guide me more on this maybe I will be able to contribute some functions here.

**Comment by technocode** [comment]
How to contact you?

I have something to discuss.

Please email me sooekuuei33 [at] gmail.com
