### ISSUE TITLE
error openssl_public_encrypt():

### ISSUE THREAD

**Issue by tenet912** [socialAPIS/Instagram-API#8]
hi . this script was work perfect but now i see this error . help plz

`Warning: openssl_public_encrypt(): key parameter is not a valid public key in C:\xampp\htdocs\zhav\autopost\src\Request\AccountRequest.php on line 257
Error occured. `

**Comment by socialAPIS** [comment]
If it doesnt work use the login_deprecated function

**Comment by tenet912** [comment]
> 
> 
> If it doesnt work use the login_deprecated function

thanks for response . but im amator , please fix this script or explain how can i use login_deprecated function . thanks
