### ISSUE TITLE
error login_required on upload photo

### ISSUE THREAD

**Issue by tenet912** [socialAPIS/Instagram-API#9]
on using script i get this error `login_required`
please help

**Comment by socialAPIS** [comment]
Did u put your credentials when using this script?

**Comment by tenet912** [comment]
> 
> 
> Did u put your credentials when using this script?

yes sir . it work last week . look my codes 
`$username = $row['a_username'];
                $pasword = $row['a_password'];

                $ig = new \InstagramFollowers\Instagram();

                try {
                    $ig->login($username, $pasword);

                    $ig->mediaRequest->UploadPhoto($base . '/uploads/'.$imageurl, $caption);

                    //get response from configure
                    $candidates = $ig->mediaRequest->configureSinglePhotoResponse->getMedia()->getImageVersions2()->getCandidates();
                    $first_candidate = $candidates[0];

                    if ($ig->mediaRequest->uploadPhotoResponse->getStatus() == 'ok') {
                        //echo "File Uploaded, your upload id is: ", $ig->mediaRequest->uploadPhotoResponse->getUploadId(), "\n";
                        echo '1';
                    }

                    //check if we are running this script on windows
                  /*  if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                        $sanitized_post_url = str_replace("&", "^^^&", $first_candidate->getUrl());
                        shell_exec("echo $sanitized_post_url | clip");
                        echo 'Windows: Your image url has been pre-copied to your clipboard. Go into browser and paste it';
                    } else {
                        echo "Copy the url and paste it in your browser\n", $first_candidate->getUrl();
                    }*/`

**Comment by socialAPIS** [comment]
I tried it, and it worked, also on 2fa. Look at the request.php file, did you put there a proxy maybe?
